#!/usr/bin/env bash
# Put universal startup things here

dunst &

#killall xclock
#xclock -geometry -0+0 &

# Put user start things in the $FVWM_USERDIR/startup directory
for file in $FVWM_USERDIR/startup/*; do
	$file;
done
