require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "c",
    "bash",
    "html",
    "javascript",
    "json",
    "lua",
    "markdown",
    "markdown_inline",
    "php",
    "python",
    "query",
    "regex",
    "rust",
    "tsx",
    "typescript",
    "vim",
    "yaml",
    "zig",
  },
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
}
